name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # If you have any tests, add the command to run them here
          echo "Running tests"

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_DEPLOY_URL  }}
        run: |
          curl -X POST $RENDER_API_KEY